In [1]:
import pandas as pd
import sqlite3 as sql
from pathlib import Path
import requests
# from IPython.display import Image
# import config

# census_api_key = '&key=' + config.census_api_key

api_summary_file_2010 = 'http://api.census.gov/data/2010/dec/sf1?'
county_pop_2010 = api_summary_file_2010 + 'get=PCT023001,PCT023003,PCT023004,PCT023005,PCT023006,PCT023014,PCT023019,PCT023020&for=COUNTY:*'

table_maker = county_pop_2010

response = requests.get(table_maker)
print(response)

<Response [200]>

In [2]:
# PCT023001 = Total population
# PCT023003 = White
# PCT023004 = Black or African American
# PCT023005 = American Indian and Alaska Native
# PCT023006 = Asian
# PCT023014 = Native Hawaiian and Other Pacific Islander
# PCT023019 = Some Other Race
# PCT023020 = Two or More Races

In [3]:
res = response.json()
res = pd.DataFrame(res)
res['FIPS'] = res[8] + res[9]
res = res.rename(columns = {0:'Total population', 1:'White', 2:'Black or African American', 3:'American Indian and Alaska Native', 4:'Asian', 5:'Native Hawaiian and Other Pacific Islander', 6:'Some Other Race', 7:'Two or More Races', 8:'State', 9:'County', 10:'FIPS'})
res = res.drop(res.index[0])
file_name = 'discard-race_county_2010'
filepath = r'..\cpst_tables\tbl-' + file_name + '.csv'
res.to_csv(filepath, index=False)
res

,Total population,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific Islander,Some Other Race,Two or More Races,State,County,FIPS
1,125744,96344,8019,2366,5102,109,9285,4519,05,131,05131
2,17058,11949,734,398,63,4,3387,523,05,133,05133
3,17264,16582,93,170,50,2,72,295,05,135,05135
4,12394,11995,11,84,45,4,55,200,05,137,05137
5,41639,26276,13721,143,207,14,756,522,05,139,05139
...,...,...,...,...,...,...,...,...,...,...,...
3217,98736,91946,874,471,3297,31,519,1598,55,035,55035
3218,4423,4306,10,31,13,1,14,48,55,037,55037
3219,101633,95674,1305,471,1148,21,1700,1314,55,039,55039
3220,9304,7690,76,1256,13,11,32,226,55,041,55041
3221,83686,78632,681,257,560,18,2479,1059,55,055,55055